#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# update event
#
event_templates('nethserver-sogo-update', qw(
      /etc/httpd/conf.d/default-virtualhost.inc
      /etc/cron.d/sogo
      /etc/sysconfig/sogo
      /etc/sogo/sogo.conf
      /etc/httpd/conf.d/SOGo.conf
      /etc/sogo/sieve.creds
      /etc/dovecot/dovecot.conf
));

event_actions('nethserver-sogo-update', qw(
      initialize-default-databases 00
      nethserver-sogo-mysqlsetup   10
      nethserver-sogo-gnustepsetup 20
      nethserver-sogo-MigrationV3.2.10ToV4.0.0 30
  ));

event_services('nethserver-sogo-update', qw(
      httpd reload
      sogod restart
      dovecot restart
));


#
# user-{create,modify,delete} events
#
event_services($_, qw(
      memcached restart
)) foreach (qw(
  user-create 
  user-modify 
  user-delete 
  domain-create 
  domain-delete 
  domain-modify
));

event_actions('user-delete', qw(
    nethserver-sogo-delete-user 80
));

#
# migration-import event
#
event_actions('migration-import', qw(
    nethserver-sogo-migrate 80
));

#
# pre-backup-data event
#
event_actions('pre-backup-data', qw(
    nethserver-sogo-backup-users 80
));


#
# nethserver-samba-* events
#
foreach (qw(
   nethserver-samba-save
   nethserver-samba-update
   nethserver-samba-adsjoin
   nethserver-sssd-save
)) {

    event_services($_, qw(
        sogod restart
        memcached restart
    ));

    event_templates($_, qw(
      /etc/sogo/sogo.conf
));

}
