#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# update event
#
event_templates('nethserver-sogo-update', qw(
      /etc/httpd/conf.d/SOGo.conf
      /etc/httpd/conf/httpd.conf
));

event_actions('nethserver-sogo-update', qw(
      initialize-default-databases 00
      nethserver-sogo-conf         01
      nethserver-sogo-ldapsetup    10
      nethserver-sogo-mysqlsetup   10
      nethserver-sogo-gnustepsetup 20
      runlevel-adjust              50
      firewall-adjust              60
));

event_services('nethserver-sogo-update', qw(
      httpd reload
));


#
# uninstall event
#
event_actions('nethserver-sogo-uninstall', qw(
      nethserver-sogo-uninstall 01
      runlevel-adjust           50
      firewall-adjust           60
));


#
# user-{create,modify,delete} events
#
event_actions($_, qw(
      memcached reload
)) foreach (qw(user-create user-modify user-delete));
