#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 1999-2005 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

#
# In nethserver-sogo-1.3.0 users was "userPrincipalName" proprerti of AD, in 1.4.0 the user name used by sogo is "sAMAccountName" [NethServer] #2778
# This script rename users inside sogo using sogo-tool. Is useful only when migrating from a 1.3.0
#

#check if AD integration is enabled
if [[ $(config getprop sogod AdsCredentials) != '' ]] ; then 
	#SOGo is configured to authenticate users on AD
	ADSERVER=$(config getprop smb AdsRealm)
	AD=$(config getprop smb Workgroup)
	ADUSER=$(config getprop sogod AdsCredentials | cut -d% -f1)
	ADPASS=$(config getprop sogod AdsCredentials | cut -d% -f2)
	DC1=$(config getprop smb AdsRealm | cut -d. -f1)
	DC2=$(config getprop smb AdsRealm | cut -d. -f2)
	MYSQLSOGOPASS=$(perl -e 'use NethServer::Directory; my $password = NethServer::Directory::getUserPassword("sogo", 0) ; printf $password;')
	for OLDUSER in $(ldapsearch -LLL -H ldap://${ADSERVER} -x -D "${AD}\\${ADUSER}" -w "${ADPASS}" -E pr=1000/noprompt -b "dc=${DC1},dc=${DC2}" | grep userPrincipalName | awk '{print $2}' ); do 
		#TODO check if user exists on DB
		if [[ $(/usr/bin/mysql sogo -usogo -p"${MYSQLSOGOPASS}" -B  -e "select count(*) from sogo_user_profile where c_uid =\"${OLDUSER}\"" | tail -n1) == 1 ]]; then
			NEWUSER=$(ldapsearch -LLL -H ldap://${ADSERVER} -x -D "${AD}\\${ADUSER}" -w "${ADPASS}" -E pr=1000/noprompt -b "dc=${DC1},dc=${DC2}" "(userPrincipalName=${i})" sAMAccountName | grep sAMAccountName | awk '{print $2}') 
			echo "renaming sogo user: $OLDUSER -> $NEWUSER"
			su - sogo -s /bin/bash -c "sogo-tool rename-user $OLDUSER $NEWUSER"
		fi
	done
fi
