#!/usr/bin/perl

#
# delete and create if needed the SOGo self hostname
#

use esmith::ConfigDB;
my $hdb = esmith::ConfigDB->open('hosts') || die("Could not open hosts db\n");
my $cdb = esmith::ConfigDB->open('configuration') || die("Could not open configuration db\n");

my $virtualhost = $cdb->get_prop('sogod','VirtualHost') || '';


foreach my $host ($hdb->get_all_by_prop('type' => 'self')) {
    my $key = $host->key;
    my $desc = $host->prop('Description') || '';
    if ($desc eq 'SOGo Virtualhost') {
        my $hostname = $hdb->get($key);
        $hostname->delete;
    }
}

if ($virtualhost ne '') {
    foreach my $hostname (split (',', $virtualhost)) {
        $hdb->set_prop($hostname,"Description", "SOGo Virtualhost",type => 'self');
    }
}

system ('/usr/sbin/e-smith/signal-event host-create');
