#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# copyright (C) 1999-2005 Mitel Networks Corporation
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

my $event = shift;
my $account = shift;;


# In the SOGo configuration UIDFieldName is set to the short_username (Ldap:uid, AD:sAMAccountName)
# strip domain from account
if ($account =~ /@/) {
    $account = (split(/@/, $account))[0];
}

# A user is unknown by SOGo if a SOGo service is never been used. 
# Exit's 0 annyway, no need to handle this. 
exec('/usr/sbin/sogo-tool', 'remove' , $account);