#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;
use NethServer::ApiTools;

my $input = NethServer::ApiTools::readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'configuration') {
    my $db = esmith::ConfigDB->open_ro();
    my %sogod = (
        ActiveSync => $db->get_prop('sogod','ActiveSync'),
        AdminUsers => $db->get_prop('sogod','AdminUsers'),
        Dav => $db->get_prop('sogod','Dav'),
        MailAuxiliaryUserAccountsEnabled => $db->get_prop('sogod','MailAuxiliaryUserAccountsEnabled'),
        Notifications => $db->get_prop('sogod','Notifications'),
        VirtualHost => $db->get_prop('sogod','VirtualHost'),
        WOWorkersCount => $db->get_prop('sogod','WOWorkersCount'),
        SOGoInternalSyncInterval => $db->get_prop('sogod','SOGoInternalSyncInterval'),
        status => $db->get_prop('sogod','status')
    );
    $ret->{'configuration'} = \%sogod;
} else {
    NethServer::ApiTools::error();
}

print encode_json($ret);
